const WORKER = 'https://joga-motion-api.omhotien90.workers.dev';
const studio = { photos: [], busy: false, videoTask: null, videoUrl: null, stage: '', message: '', uncertain: false, detail: '' };
const TEXT = {
 es: {eyebrow:'TU ESTUDIO DE VIDEO CON IA',title:'Imagina la historia. Crea el video.',subtitle:'Tus imágenes y una idea. Nosotros les damos movimiento.',heroAction:'Crear mi video',photos:'Añade tu imagen',upload:'Subir imagen',formats:'1 imagen · JPG, PNG o WebP · 10 MB',referenceHint:'Describe el movimiento que quieres ver en esta imagen.',description:'¿Qué quieres que pase?',placeholder:'Por ejemplo: la persona de la foto sonríe y la cámara se acerca lentamente.',spec:'Video de 5 s · Horizontal',create:'Crear video',resume:'Continuar video',again:'Crear otra versión',working:'Creando tu video…',preview:'Tu video',previewTag:'VISTA PREVIA',emptyTitle:'Tu historia empieza aquí',emptyText:'Añade tus imágenes, describe la acción y mira cómo cobra vida.',previewHint:'El resultado aparecerá aquí, listo para reproducir y descargar.',download:'Descargar video',progressNote:'Puedes dejar esta página abierta mientras se crea tu video.',animating:'Dando movimiento a tu historia…',cost:'Cada creación usa una generación de video.',footer:'Mantén esta página abierta. Al recargar se pierde el proyecto. Editar las fotos o la descripción inicia una creación nueva.',invalid:'Usa imágenes JPG, PNG o WebP de hasta 10 MB.',waiting:'La consulta se interrumpió. Pulsa Continuar video para consultar el mismo trabajo sin enviarlo otra vez.',failed:'El proveedor no pudo completar la generación. Puedes intentarlo de nuevo.',outdated:'Falta actualizar el Worker en Cloudflare para esta función.',uncertain:'No se pudo confirmar el envío. Revisa tu actividad en Higgsfield antes de crear otra versión: podría haberse generado un cargo.',ready:'Tu video está listo.',remove:'Quitar imagen ',photo:'Imagen ',retry:'Intentar de nuevo',error:'No se pudo completar la solicitud.'},
 en: {eyebrow:'YOUR AI VIDEO STUDIO',title:'Imagine the story. Create the video.',subtitle:'Your images and an idea. We bring them to life.',heroAction:'Create my video',photos:'Add your image',upload:'Upload image',formats:'1 image · JPG, PNG or WebP · 10 MB',referenceHint:'Describe the motion you want to see in this image.',description:'What would you like to happen?',placeholder:'For example: the person in the photo smiles and the camera slowly zooms in.',spec:'5-second video · Landscape',create:'Create video',resume:'Continue video',again:'Create another version',working:'Creating your video…',preview:'Your video',previewTag:'PREVIEW',emptyTitle:'Your story starts here',emptyText:'Add your images, describe the action and watch it come to life.',previewHint:'Your result will appear here, ready to play and download.',download:'Download video',progressNote:'Keep this page open while your video is created.',animating:'Bringing your story to life…',cost:'Each creation uses one video generation.',footer:'Keep this page open. Reloading loses the project. Editing the photos or description starts a new creation.',invalid:'Use JPG, PNG or WebP images up to 10 MB.',waiting:'The status check was interrupted. Press Continue video to check the same job without submitting it again.',failed:'The provider could not complete the generation. You can try again.',outdated:'The Cloudflare Worker needs updating for this feature.',uncertain:'Could not confirm submission. Check your Higgsfield activity before creating another version: a charge may have occurred.',ready:'Your video is ready.',remove:'Remove image ',photo:'Image ',retry:'Try again',error:'Could not complete the request.'}
};
let language;try{language=localStorage.getItem('jiLang')==='en'?'en':'es';}catch{language='es';}
const $=id=>document.getElementById(id), t=key=>TEXT[language][key];
function resetGeneration(){studio.videoTask=null;studio.videoUrl=null;studio.stage='';studio.message='';studio.detail='';studio.uncertain=false;$('video').pause();$('video').removeAttribute('src');$('download').removeAttribute('href');}
function render(){
 document.documentElement.lang=language;document.title='Joga Motion — '+t('create');
 document.querySelectorAll('[data-copy]').forEach(el=>el.textContent=t(el.dataset.copy));
 $('language').textContent=language==='es'?'English':'Español';$('description').placeholder=t('placeholder');
 $('photoCount').textContent=studio.photos.length+' / 1';$('upload').disabled=studio.busy;$('photos').disabled=studio.busy;
 $('description').disabled=studio.busy;
 $('create').disabled=studio.busy||!studio.photos.length||!$('description').value.trim();
 $('create').textContent=t(studio.busy?'working':studio.videoUrl?'again':studio.videoTask?'resume':studio.message==='failed'?'retry':'create');
 $('progress').hidden=!studio.busy;$('progressTitle').textContent=t('animating');
 $('emptyPreview').hidden=studio.busy||Boolean(studio.videoUrl);$('video').hidden=!studio.videoUrl;
 $('download').hidden=!studio.videoUrl;$('message').textContent=(studio.message?t(studio.message):'')+(studio.detail?' ('+studio.detail+')':'');
 $('thumbnails').replaceChildren();
 studio.photos.forEach((photo,i)=>{const item=document.createElement('figure');item.className='thumbnail';const img=document.createElement('img');img.src=photo.url;img.alt=photo.file.name;const cap=document.createElement('figcaption');cap.textContent=t('photo')+(i+1);const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',t('remove')+(i+1));remove.disabled=studio.busy;remove.onclick=()=>{URL.revokeObjectURL(photo.url);studio.photos.splice(i,1);resetGeneration();render();};item.append(img,cap,remove);$('thumbnails').append(item);});
 $('examples').replaceChildren();
 const samples=language==='es'?[['Sonrisa y acercamiento','La persona de la foto sonríe y la cámara se acerca lentamente.'],['Paisaje con viento','El paisaje cobra vida con viento suave y luz de amanecer.'],['Zoom con partículas','Zoom lento hacia el centro con partículas de luz.']]:[['Smile and zoom in','The person in the photo smiles and the camera slowly zooms in.'],['Landscape with wind','The landscape comes alive with gentle wind and sunrise light.'],['Zoom with particles','Slow zoom toward the center with particles of light.']];
 samples.forEach(([label,prompt])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=studio.busy;b.onclick=()=>{$('description').value=prompt;resetGeneration();render();};$('examples').append(b);});
}
function addPhotos(files){if(studio.busy)return;let error='';let changed=false;for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||!file.size||file.size>10*1024*1024){error='invalid';continue;}if(studio.photos.length){URL.revokeObjectURL(studio.photos[0].url);studio.photos.length=0;}studio.photos.push({file,url:URL.createObjectURL(file)});changed=true;break;}if(changed)resetGeneration();if(error)studio.message=error;render();}
async function request(path,options){const res=await fetch(WORKER+path,{...options,signal:AbortSignal.timeout(120000)});if(!res.ok){let detail='';try{detail=String((await res.clone().json()).error||'');}catch{}const e=new Error('Request failed');e.outdated=res.status===404&&!detail;e.rejected=res.status>=400&&res.status<500;e.detail=detail;throw e;}return res;}
async function status(path,id){let fallos=0;for(let i=0;i<120;i++){let data;try{data=await(await request(path+'?task_id='+encodeURIComponent(id))).json();fallos=0;}catch(e){if(e.rejected||e.outdated)throw e;if(++fallos>=12){const w=new Error('Status unavailable');w.detail=e.detail||'';throw w;}await new Promise(r=>setTimeout(r,5000));continue;}if(data.status==='completed')return data;if(data.status==='failed'){const e=new Error('Generation failed');e.terminal=true;e.detail=String(data.error||'');throw e;}await new Promise(r=>setTimeout(r,5000));}throw new Error('Still processing');}
async function createVideo(){
 if(studio.busy||!studio.photos.length||!$('description').value.trim())return;
 if(studio.uncertain&&!window.confirm(t('uncertain')))return;
 if(studio.videoUrl)resetGeneration();studio.busy=true;studio.message='';studio.detail='';let submitting=false;
 const prompt=$('description').value.trim();
 try{
  studio.stage='video';render();
  if(!studio.videoTask){const form=new FormData();form.append('image',studio.photos[0].file);form.append('prompt',prompt);form.append('duration','5');submitting=true;const job=await(await request('/generate',{method:'POST',body:form})).json();if(!job.task_id)throw new Error('Missing task');studio.videoTask=job.task_id;submitting=false;}
  const video=await status('/status',studio.videoTask);if(!video.video_url)throw new Error('Missing video');studio.videoUrl=video.video_url;$('video').src=studio.videoUrl;$('download').href=WORKER+'/download?task_id='+encodeURIComponent(studio.videoTask);$('download').target='_blank';$('download').rel='noopener';studio.message='ready';studio.uncertain=false;
 }catch(e){
  if(e.terminal){studio.videoTask=null;studio.message='failed';studio.detail=e.detail||'';}
  else if(e.outdated)studio.message='outdated';
  else if(!submitting&&studio.videoTask&&!e.rejected){studio.message='waiting';studio.detail=e.detail||'';}
  else if(e.detail){studio.message='error';studio.detail=e.detail;}
  else if(submitting&&!e.rejected){studio.uncertain=true;studio.message='uncertain';}
  else studio.message=studio.videoTask?'waiting':'error';
 }finally{studio.busy=false;render();}
}
$('upload').onclick=()=>$('photos').click();$('photos').onchange=e=>{addPhotos(Array.from(e.target.files));e.target.value='';};
$('upload').ondragover=e=>{e.preventDefault();if(!studio.busy)$('upload').classList.add('drag');};$('upload').ondragleave=()=>$('upload').classList.remove('drag');$('upload').ondrop=e=>{e.preventDefault();$('upload').classList.remove('drag');addPhotos(Array.from(e.dataTransfer.files));};
$('description').oninput=()=>{resetGeneration();render();};$('create').onclick=createVideo;$('language').onclick=()=>{language=language==='es'?'en':'es';try{localStorage.setItem('jiLang',language);}catch{}render();};render();
