const WORKER = 'https://joga-motion-api.omhotien90.workers.dev';
const studio = { photos: [], busy: false, imageTask: null, imageReady: false, videoTask: null, videoUrl: null, stage: '', message: '', uncertain: false };
const TEXT = {
 es: {eyebrow:'TU ESTUDIO DE VIDEO CON IA',title:'Imagina la historia. Crea el video.',subtitle:'Tus imágenes y una idea. Nosotros les damos movimiento.',heroAction:'Crear mi video',photos:'Añade tus imágenes',upload:'Subir imágenes',formats:'Hasta 8 imágenes · JPG, PNG o WebP · 10 MB por imagen',referenceHint:'Úsalas como referencias para un solo video. Describe qué personas, objetos o lugares quieres incluir.',description:'¿Qué quieres que pase?',placeholder:'Por ejemplo: las personas de las fotos caminan juntas por una montaña al amanecer, sonríen y saludan a la cámara.',spec:'Video de 5 s · Horizontal',create:'Crear video',resume:'Continuar video',again:'Crear otra versión',working:'Creando tu video…',preview:'Tu video',previewTag:'VISTA PREVIA',emptyTitle:'Tu historia empieza aquí',emptyText:'Añade tus imágenes, describe la acción y mira cómo cobra vida.',previewHint:'El resultado aparecerá aquí, listo para reproducir y descargar.',download:'Descargar video',progressNote:'Puedes dejar esta página abierta mientras se crea tu video.',composing:'Preparando tu escena…',animating:'Dando movimiento a tu historia…',cost:'Cada creación usa una generación de imagen y una de video. El parecido y las acciones pueden variar.',footer:'Mantén esta página abierta. Al recargar se pierde el proyecto. Editar las fotos o la descripción inicia una creación nueva.',limit:'Puedes añadir hasta 8 imágenes.',invalid:'Usa imágenes JPG, PNG o WebP de hasta 10 MB.',waiting:'La consulta se interrumpió. Pulsa Continuar video para consultar el mismo trabajo sin enviarlo otra vez.',failed:'El proveedor no pudo completar la generación. Puedes intentarlo de nuevo.',outdated:'Falta actualizar el Worker en Cloudflare para esta función.',uncertain:'No se pudo confirmar el envío. Revisa tu actividad en Higgsfield antes de crear otra versión: podría haberse generado un cargo.',ready:'Tu video está listo.',remove:'Quitar imagen ',photo:'Imagen ',retry:'Intentar de nuevo',error:'No se pudo completar la solicitud.'},
 en: {eyebrow:'YOUR AI VIDEO STUDIO',title:'Imagine the story. Create the video.',subtitle:'Your images and an idea. We bring them to life.',heroAction:'Create my video',photos:'Add your images',upload:'Upload images',formats:'Up to 8 images · JPG, PNG or WebP · 10 MB per image',referenceHint:'Use them as references for one video. Describe the people, objects or places you want to include.',description:'What would you like to happen?',placeholder:'For example: the people in the photos walk together on a mountain at sunrise, smile and wave to the camera.',spec:'5-second video · Landscape',create:'Create video',resume:'Continue video',again:'Create another version',working:'Creating your video…',preview:'Your video',previewTag:'PREVIEW',emptyTitle:'Your story starts here',emptyText:'Add your images, describe the action and watch it come to life.',previewHint:'Your result will appear here, ready to play and download.',download:'Download video',progressNote:'Keep this page open while your video is created.',composing:'Preparing your scene…',animating:'Bringing your story to life…',cost:'Each creation uses one image generation and one video generation. Likeness and actions may vary.',footer:'Keep this page open. Reloading loses the project. Editing the photos or description starts a new creation.',limit:'You can add up to 8 images.',invalid:'Use JPG, PNG or WebP images up to 10 MB.',waiting:'The status check was interrupted. Press Continue video to check the same job without submitting it again.',failed:'The provider could not complete the generation. You can try again.',outdated:'The Cloudflare Worker needs updating for this feature.',uncertain:'Could not confirm submission. Check your Higgsfield activity before creating another version: a charge may have occurred.',ready:'Your video is ready.',remove:'Remove image ',photo:'Image ',retry:'Try again',error:'Could not complete the request.'}
};
let language;try{language=localStorage.getItem('jiLang')==='en'?'en':'es';}catch{language='es';}
const $=id=>document.getElementById(id), t=key=>TEXT[language][key];
function resetGeneration(){studio.imageTask=null;studio.imageReady=false;studio.videoTask=null;studio.videoUrl=null;studio.stage='';studio.message='';studio.uncertain=false;$('video').pause();$('video').removeAttribute('src');$('download').removeAttribute('href');}
function render(){
 document.documentElement.lang=language;document.title='Joga Motion — '+t('create');
 document.querySelectorAll('[data-copy]').forEach(el=>el.textContent=t(el.dataset.copy));
 $('language').textContent=language==='es'?'English':'Español';$('description').placeholder=t('placeholder');
 $('photoCount').textContent=studio.photos.length+' / 8';$('upload').disabled=studio.busy||studio.photos.length===8;$('photos').disabled=studio.busy;
 $('description').disabled=studio.busy;
 $('create').disabled=studio.busy||!studio.photos.length||!$('description').value.trim();
 $('create').textContent=t(studio.busy?'working':studio.videoUrl?'again':studio.imageTask||studio.videoTask?'resume':studio.message==='failed'?'retry':'create');
 $('progress').hidden=!studio.busy;$('progressTitle').textContent=t(studio.stage==='video'?'animating':'composing');
 $('emptyPreview').hidden=studio.busy||Boolean(studio.videoUrl);$('video').hidden=!studio.videoUrl;
 $('download').hidden=!studio.videoUrl;$('message').textContent=studio.message?t(studio.message):'';
 $('thumbnails').replaceChildren();
 studio.photos.forEach((photo,i)=>{const item=document.createElement('figure');item.className='thumbnail';const img=document.createElement('img');img.src=photo.url;img.alt=photo.file.name;const cap=document.createElement('figcaption');cap.textContent=t('photo')+(i+1);const remove=document.createElement('button');remove.type='button';remove.textContent='×';remove.setAttribute('aria-label',t('remove')+(i+1));remove.disabled=studio.busy;remove.onclick=()=>{URL.revokeObjectURL(photo.url);studio.photos.splice(i,1);resetGeneration();render();};item.append(img,cap,remove);$('thumbnails').append(item);});
 $('examples').replaceChildren();
 const samples=language==='es'?[['En la montaña','Las personas de las fotos caminan juntas por una montaña al amanecer, sonríen y saludan a la cámara.'],['A caballo','Las personas de las fotos cabalgan lado a lado por una pradera al atardecer.'],['En un carro','Las personas de las fotos viajan juntas en un carro por una carretera costera. La persona que conduce mira al frente.']]:[['On a mountain','The people in the photos walk together on a mountain at sunrise, smile and wave to the camera.'],['Horse riding','The people in the photos ride horses side by side through a meadow at sunset.'],['In a car','The people in the photos travel together in a car along a coastal road. The driver looks ahead.']];
 samples.forEach(([label,prompt])=>{const b=document.createElement('button');b.type='button';b.textContent=label;b.disabled=studio.busy;b.onclick=()=>{$('description').value=prompt;resetGeneration();render();};$('examples').append(b);});
}
function addPhotos(files){if(studio.busy)return;let error='';let changed=false;for(const file of files){if(!['image/jpeg','image/png','image/webp'].includes(file.type)||!file.size||file.size>10*1024*1024){error='invalid';continue;}if(studio.photos.length>=8){error='limit';break;}studio.photos.push({file,url:URL.createObjectURL(file)});changed=true;}if(changed)resetGeneration();if(error)studio.message=error;render();}
async function request(path,options){const res=await fetch(WORKER+path,{...options,signal:AbortSignal.timeout(120000)});if(!res.ok){const e=new Error('Request failed');e.outdated=res.status===404;e.rejected=res.status>=400&&res.status<500;throw e;}return res;}
async function status(path,id){for(let i=0;i<120;i++){const data=await(await request(path+'?task_id='+encodeURIComponent(id))).json();if(data.status==='completed')return data;if(data.status==='failed'){const e=new Error('Generation failed');e.terminal=true;throw e;}await new Promise(r=>setTimeout(r,5000));}throw new Error('Still processing');}
async function createVideo(){
 if(studio.busy||!studio.photos.length||!$('description').value.trim())return;
 if(studio.uncertain&&!window.confirm(t('uncertain')))return;
 if(studio.videoUrl)resetGeneration();studio.busy=true;studio.message='';let submitting=false;
 const prompt=$('description').value.trim();
 try{
  studio.stage='image';render();
  if(!studio.imageTask){const form=new FormData();studio.photos.forEach(p=>form.append('images',p.file));form.append('prompt',prompt);form.append('aspect_ratio','16:9');submitting=true;const job=await(await request('/compose',{method:'POST',body:form})).json();if(!job.task_id)throw new Error('Missing task');studio.imageTask=job.task_id;submitting=false;}
  if(!studio.imageReady){const image=await status('/compose-status',studio.imageTask);if(!image.image_url)throw new Error('Missing image');studio.imageReady=true;}
  studio.stage='video';render();
  if(!studio.videoTask){const res=await request('/compose-image?task_id='+encodeURIComponent(studio.imageTask));const blob=await res.blob();if(!['image/jpeg','image/png','image/webp'].includes(blob.type)||!blob.size||blob.size>10*1024*1024)throw new Error('Invalid generated image');const form=new FormData();form.append('image',new File([blob],'scene.jpg',{type:blob.type}));form.append('prompt',prompt);form.append('duration','5');submitting=true;const job=await(await request('/generate',{method:'POST',body:form})).json();if(!job.task_id)throw new Error('Missing task');studio.videoTask=job.task_id;submitting=false;}
  const video=await status('/status',studio.videoTask);if(!video.video_url)throw new Error('Missing video');studio.videoUrl=video.video_url;$('video').src=studio.videoUrl;$('download').href=WORKER+'/download?task_id='+encodeURIComponent(studio.videoTask);$('download').target='_blank';$('download').rel='noopener';studio.message='ready';studio.uncertain=false;
 }catch(e){
  if(e.terminal){if(studio.stage==='image'){studio.imageTask=null;studio.imageReady=false;}else studio.videoTask=null;studio.message='failed';}
  else if(e.outdated)studio.message='outdated';
  else if(submitting&&!e.rejected){studio.uncertain=true;studio.message='uncertain';}
  else studio.message=studio.imageTask||studio.videoTask?'waiting':'error';
 }finally{studio.busy=false;render();}
}
$('upload').onclick=()=>$('photos').click();$('photos').onchange=e=>{addPhotos(Array.from(e.target.files));e.target.value='';};
$('upload').ondragover=e=>{e.preventDefault();if(!studio.busy)$('upload').classList.add('drag');};$('upload').ondragleave=()=>$('upload').classList.remove('drag');$('upload').ondrop=e=>{e.preventDefault();$('upload').classList.remove('drag');addPhotos(Array.from(e.dataTransfer.files));};
$('description').oninput=()=>{resetGeneration();render();};$('create').onclick=createVideo;$('language').onclick=()=>{language=language==='es'?'en':'es';try{localStorage.setItem('jiLang',language);}catch{}render();};render();
